modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/skippi/graveler/issues"

[[mods]]
modId="graveler"
version="${file.jarVersion}"
displayName="Graveler"
displayURL="https://github.com/skippi/graveler"
authors="skippi"
description='''A Minecraft mod that applies gravity to unstable structures.'''

[[dependencies.graveler]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.graveler]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
